version: '3.8'
services:
    apt-cacher-ng:
        container_name: apt-cacher-ng
        image: konstruktoid/apt-cacher-ng
        ports:
            - 3142:3142
        volumes:
            - apt-cache:/var/cache/apt-cacher-ng
        restart: unless-stopped
volumes:
    apt-cache:
